-- CREATE AND MOVE TO DATABASE
CREATE DATABASE softjobs;
\c softjobs;

-- CREATE TABLE
CREATE TABLE users (id SERIAL PRIMARY KEY NOT NULL,
email VARCHAR(50) NOT NULL UNIQUE,
password VARCHAR(60) NOT NULL,
role VARCHAR(25) NOT NULL,
lenguage VARCHAR(20) NOT NULL,
created_at TIMESTAMP NOT NULL DEFAULT NOW(),
updated_at TIMESTAMP NOT NULL DEFAULT NOW());

-- FUNCTION THAT UPDATES THE update_at COLUMN EVERY TIME WE MAKE A CHANGE
CREATE FUNCTION update_updated_at_users()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_users_updated_at
    BEFORE UPDATE
    ON
        users
    FOR EACH ROW
EXECUTE PROCEDURE update_updated_at_users();

-- ONE LINE CREATE TABLE
CREATE TABLE users (id SERIAL PRIMARY KEY NOT NULL, email VARCHAR(50) NOT NULL UNIQUE, password VARCHAR(60) NOT NULL, role VARCHAR(25) NOT NULL, lenguage VARCHAR(20) NOT NULL);